name: tem-seg-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12

  # Core scientific computing
  - numpy<2.2
  - scipy>=1.15.2
  - pandas>=2.2.3
  - matplotlib>=3.10.1
  - seaborn>=0.13.2

  # Machine learning and deep learning
  - scikit-learn>=1.6.1

  # Image processing
  - pillow>=11.1.0
  - opencv>=4.11.0

  # Development tools
  - ipykernel>=6.29.5
  - jupyter
  - ipython

  # Configuration and CLI
  - toml>=0.10.2
  - typer>=0.16.0
  - pydantic>=2.11.0
  - pydantic-settings>=2.10.1

  # Additional dependencies from pip
  - pip
  - pip:
    - tensorflow[and-cuda]>=2.16.0; sys_platform=="linux"
    - tensorflow>=2.16.0; sys_platform=="win32" or sys_platform=="darwin"
    - tensorflow-metal; sys_platform=="darwin"
