[environment]
debug = false
tf_cpp_min_log_level = "2"

[assets]
path = "~/.tem-seg/assets"

[assets.model_weights]
version = "1.0.0"
mirrors = [
    "https://zenodo.org/records/15602446/files/tem-seg-models_v1.0.0.tar.gz?download=1",
]
filename = "tem-seg-models_v1.0.0.tar.gz"
sha256 = "525635b333bbbcac3e355bc306f39f7f270ac8398c7f69a114085b385199cb92"
md5 = "454cd082fa1d0dbac129d717f6a90341"
